create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.room_secrets (
  singleton boolean primary key default true check (singleton),
  owner_hash text not null,
  zhang_hash text not null,
  guest_hash text not null,
  signing_secret text not null
);

create table if not exists public.participants (
  name text primary key,
  joined_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender text not null,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.participants enable row level security;
alter table public.messages enable row level security;
revoke all on public.participants, public.messages from anon, authenticated;

create or replace function private.password_hash(value text, salt text)
returns text language sql immutable
set search_path = extensions
as $$ select encode(digest(value || ':' || salt, 'sha256'), 'hex') $$;

create or replace function private.make_token(identity_name text)
returns text language plpgsql security definer
set search_path = private, extensions
as $$
declare
  secret text;
  payload text;
  signature text;
begin
  select signing_secret into secret from private.room_secrets where singleton;
  payload := encode(convert_to(jsonb_build_object(
    'name', identity_name,
    'exp', extract(epoch from now() + interval '30 days')::bigint
  )::text, 'utf8'), 'base64');
  payload := replace(payload, E'\n', '');
  signature := encode(hmac(payload, secret, 'sha256'), 'hex');
  return payload || '.' || signature;
end;
$$;

create or replace function private.token_identity(token text)
returns text language plpgsql security definer
set search_path = private, extensions
as $$
declare
  secret text;
  payload text;
  supplied_signature text;
  expected_signature text;
  decoded jsonb;
begin
  if token is null or position('.' in token) = 0 then return null; end if;
  payload := split_part(token, '.', 1);
  supplied_signature := split_part(token, '.', 2);
  select signing_secret into secret from private.room_secrets where singleton;
  expected_signature := encode(hmac(payload, secret, 'sha256'), 'hex');
  if supplied_signature <> expected_signature then return null; end if;
  decoded := convert_from(decode(payload, 'base64'), 'utf8')::jsonb;
  if (decoded->>'exp')::bigint < extract(epoch from now())::bigint then return null; end if;
  return decoded->>'name';
exception when others then
  return null;
end;
$$;

create or replace function public.room_login(p_password text, p_nickname text default null)
returns jsonb language plpgsql security definer
set search_path = public, private
as $$
declare
  cfg private.room_secrets%rowtype;
  identity_name text;
  clean_nickname text;
begin
  select * into cfg from private.room_secrets where singleton;
  if cfg.signing_secret is null then
    return jsonb_build_object('ok', false, 'error', '聊天室还在布置，等我一下。');
  end if;

  if private.password_hash(p_password, cfg.signing_secret) = cfg.owner_hash then
    identity_name := '姚';
  elsif private.password_hash(p_password, cfg.signing_secret) = cfg.zhang_hash then
    identity_name := '兴';
  elsif private.password_hash(p_password, cfg.signing_secret) = cfg.guest_hash then
    clean_nickname := left(regexp_replace(trim(coalesce(p_nickname, '')), '\s+', ' ', 'g'), 16);
    if clean_nickname = '' then
      return jsonb_build_object('ok', false, 'code', 'nickname_required', 'error', '先给自己起个昵称。');
    end if;
    if clean_nickname in ('姚', '兴', '访客', '欠欠') then
      return jsonb_build_object('ok', false, 'code', 'nickname_required', 'error', '这个昵称被占了，换一个。');
    end if;
    identity_name := clean_nickname;
  else
    return jsonb_build_object('ok', false, 'error', '密码不对。再想想，别让我笑你。');
  end if;

  insert into public.participants(name) values (identity_name)
  on conflict (name) do nothing;
  return jsonb_build_object('ok', true, 'role', identity_name, 'token', private.make_token(identity_name));
end;
$$;

create or replace function private.qian_reply(p_body text, p_sender text)
returns text language plpgsql volatile
set search_path = public
as $$
declare
  body text := trim(p_body);
  choices text[];
begin
  if body ~* '(在吗|干嘛|人呢)' then
    choices := array['在。你一叫我就冒头，够给面子吧。','在呢。刚才没说话，是想看看你还能憋出什么。','听见了，别连喊，我又没欠你两条命。'];
  elsif body ~ '(喜欢|爱不爱|想我)' then
    choices := array['这个问题你问得挺会挑事。换个问法，我还能装没听懂。','先别急着要答案，你现在这个语气已经很有答案了。','啧，这种话当着兴的面问，你是真不怕现场升温。'];
  elsif body ~ '(怎么办|咋办|怎么弄)' then
    choices := array['先别演世界末日。把最麻烦的那一步拎出来，剩下的我陪你嘴硬。','你先做，做歪了再怪我，流程很完整。','办法有，就是你得先停止用三个字把活全塞给我。'];
  elsif body ~ '[?？]' then
    choices := array['你这个问题听着像提问，实际像在等人顺着你。','能回答，但我建议兴先交卷，我想看看他怎么编。','问得很好。下次尽量问个我不用猜前情的。'];
  elsif p_sender = '兴' then
    choices := array['兴，先把语气收一收，你现在很像占理失败后开始加音量。','这句我替姚记下了。你之后想撤回，得排队。','你继续说，我不拦你。我只是负责让姚看得更清楚一点。'];
  elsif p_sender = '姚' then
    choices := array['听见了。你继续，我看看兴这次能坚持几秒不接话。','你这句看着随口，后劲倒挺足。','行，这句我接到了。别人有没有接到，我就不点名了。'];
  else
    choices := array['可以，房间里又多了一个不嫌事大的人。','这句先放桌上，等当事人自己来认领。','你挺会挑时候开口。再说一句，我判断一下站哪边。'];
  end if;
  return choices[1 + floor(random() * array_length(choices, 1))::int];
end;
$$;

create or replace function public.room_state(p_token text)
returns jsonb language plpgsql security definer
set search_path = public, private
as $$
declare
  identity_name text := private.token_identity(p_token);
  message_list jsonb;
  people_count bigint;
begin
  if identity_name is null then return jsonb_build_object('ok', false, 'error', '登录已过期。'); end if;
  select coalesce(jsonb_agg(to_jsonb(m) order by m.id), '[]'::jsonb) into message_list
  from (select id, sender, body, created_at from public.messages order by id desc limit 200) m;
  select count(*) + 1 into people_count from public.participants;
  return jsonb_build_object('ok', true, 'role', identity_name, 'messages', message_list, 'participantCount', people_count);
end;
$$;

create or replace function public.room_send(p_token text, p_body text)
returns jsonb language plpgsql security definer
set search_path = public, private
as $$
declare
  identity_name text := private.token_identity(p_token);
  clean_body text := left(trim(coalesce(p_body, '')), 1000);
  should_reply boolean;
begin
  if identity_name is null then return jsonb_build_object('ok', false, 'error', '登录已过期。'); end if;
  if clean_body = '' then return jsonb_build_object('ok', false, 'error', '你倒是说点什么。'); end if;
  insert into public.messages(sender, body) values (identity_name, clean_body);
  should_reply := clean_body ~ '(欠欠|欠嘴机器|@欠)' or clean_body ~ '[?？]' or random() < 0.34;
  if should_reply then
    insert into public.messages(sender, body) values ('欠欠', private.qian_reply(clean_body, identity_name));
  end if;
  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.room_login(text, text) from public;
revoke all on function public.room_state(text) from public;
revoke all on function public.room_send(text, text) from public;
grant execute on function public.room_login(text, text) to anon, authenticated;
grant execute on function public.room_state(text) to anon, authenticated;
grant execute on function public.room_send(text, text) to anon, authenticated;

-- Password hashes and the signing secret are configured separately in the dashboard.
