create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.room_secrets (
  singleton boolean primary key default true check (singleton),
  owner_hash text not null,
  zhang_hash text not null,
  guest_hash text not null,
  signing_secret text not null
);

create table if not exists public.participants (
  name text primary key,
  joined_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender text not null,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.participants enable row level security;
alter table public.messages enable row level security;
revoke all on public.participants, public.messages from anon, authenticated;

create or replace function private.password_hash(value text, salt text)
returns text language sql immutable
set search_path = extensions
as $$ select encode(digest(value || ':' || salt, 'sha256'), 'hex') $$;

create or replace function private.make_token(identity_name text)
returns text language plpgsql security definer
set search_path = private, extensions
as $$
declare
  secret text;
  payload text;
  signature text;
begin
  select signing_secret into secret from private.room_secrets where singleton;
  payload := encode(convert_to(jsonb_build_object(
    'name', identity_name,
    'exp', extract(epoch from now() + interval '30 days')::bigint
  )::text, 'utf8'), 'base64');
  payload := replace(payload, E'\n', '');
  signature := encode(hmac(payload, secret, 'sha256'), 'hex');
  return payload || '.' || signature;
end;
$$;

create or replace function private.token_identity(token text)
returns text language plpgsql security definer
set search_path = private, extensions
as $$
declare
  secret text;
  payload text;
  supplied_signature text;
  expected_signature text;
  decoded jsonb;
begin
  if token is null or position('.' in token) = 0 then return null; end if;
  payload := split_part(token, '.', 1);
  supplied_signature := split_part(token, '.', 2);
  select signing_secret into secret from private.room_secrets where singleton;
  expected_signature := encode(hmac(payload, secret, 'sha256'), 'hex');
  if supplied_signature <> expected_signature then return null; end if;
  decoded := convert_from(decode(payload, 'base64'), 'utf8')::jsonb;
  if (decoded->>'exp')::bigint < extract(epoch from now())::bigint then return null; end if;
  return decoded->>'name';
exception when others then
  return null;
end;
$$;

create or replace function public.room_login(p_password text, p_nickname text default null)
returns jsonb language plpgsql security definer
set search_path = public, private
as $$
declare
  cfg private.room_secrets%rowtype;
  identity_name text;
  clean_nickname text;
begin
  select * into cfg from private.room_secrets where singleton;
  if cfg.signing_secret is null then
    return jsonb_build_object('ok', false, 'error', '聊天室还在布置，等我一下。');
  end if;

  if private.password_hash(p_password, cfg.signing_secret) = cfg.owner_hash then
    identity_name := '姚';
  elsif private.password_hash(p_password, cfg.signing_secret) = cfg.zhang_hash then
    identity_name := '兴';
  elsif private.password_hash(p_password, cfg.signing_secret) = cfg.guest_hash then
    clean_nickname := left(regexp_replace(trim(coalesce(p_nickname, '')), '\s+', ' ', 'g'), 16);
    if clean_nickname = '' then
      return jsonb_build_object('ok', false, 'code', 'nickname_required', 'error', '先给自己起个昵称。');
    end if;
    if clean_nickname in ('姚', '兴', '访客', '欠欠') then
      return jsonb_build_object('ok', false, 'code', 'nickname_required', 'error', '这个昵称被占了，换一个。');
    end if;
    identity_name := clean_nickname;
  else
    return jsonb_build_object('ok', false, 'error', '密码不对。再想想，别让我笑你。');
  end if;

  insert into public.participants(name) values (identity_name)
  on conflict (name) do nothing;
  return jsonb_build_object('ok', true, 'role', identity_name, 'token', private.make_token(identity_name));
end;
$$;

create or replace function private.qian_replies(p_body text, p_sender text)
returns text[] language plpgsql volatile
set search_path = public
as $$
declare
  body text := trim(p_body);
  choices jsonb;
  chosen jsonb;
  picked text[];
begin
  if body ~ '(谁是欠欠|欠欠是谁)' then
    return array['我。', '刚来的？先报个名。'];
  elsif body ~ '(哈喽|你好|嗨|hello|Hello)' then
    if p_sender = '姚' then return array['哟，今天这么客气。', '兴呢，没跟来？']; end if;
    return array['哈喽。', '你哪位？'];
  elsif body ~ '(兴|张兴宇).*(睡了|睡啦|睡着|睡觉)' then
    return array['这么早？那我现在说他坏话，他也看不见。', '……算了，明天他会翻记录。'];
  elsif body ~ '(你们|怎么|咋).*(不说话|没说话|没声|不理我)' then
    return array['兴不是睡了吗。', '其他人估计在潜水。', '现在就我理你，感动不？'];
  elsif body ~* '(在吗|干嘛|人呢)' then
    choices := jsonb_build_array(jsonb_build_array('在。','喊这么大声干嘛。'), jsonb_build_array('在呢。','刚准备装没看见。'), jsonb_build_array('干嘛？','先说好，借钱没有。'));
  elsif body ~ '(喜欢|爱不爱|想我)' then
    choices := jsonb_build_array(jsonb_build_array('问这个干嘛。','兴还在房间里呢。'), jsonb_build_array('有一点吧。','别截图，我会不认。'), jsonb_build_array('你先问兴。','我排他后面，省得他又翻。'));
  elsif body ~ '(怎么办|咋办|怎么弄)' then
    choices := jsonb_build_array(jsonb_build_array('你先把事情说完整。','三个字就想让我接管人生啊？'), jsonb_build_array('先做最急的那个。','做歪了再回来怪我。'), jsonb_build_array('我哪知道。','但我可以先陪你骂两句。'));
  elsif body ~ '[?？]' then
    choices := jsonb_build_array(jsonb_build_array('不知道。','你再说具体点。'), jsonb_build_array('你先说你想听哪个答案。'), jsonb_build_array('等下。','这题应该先让兴答。'));
  elsif p_sender = '兴' then
    choices := jsonb_build_array(jsonb_build_array('兴，你先别急。','急了就更像心虚。'), jsonb_build_array('行，我记住了。','等姚上线我原样复述。'), jsonb_build_array('你继续。','我看你还能嘴硬多久。'));
  elsif p_sender = '姚' then
    choices := jsonb_build_array(jsonb_build_array('嗯？','然后呢。'), jsonb_build_array('行。','这次先站你这边。'), jsonb_build_array('你接着说。','我在听。'), jsonb_build_array('可以。','但兴看见估计又要说我偏心。'));
  else
    choices := jsonb_build_array(jsonb_build_array('我，欠欠。','你叫什么？'), jsonb_build_array('看见了。','继续。'), jsonb_build_array('你先说。','我暂时不打断。'));
  end if;
  chosen := choices -> floor(random() * jsonb_array_length(choices))::int;
  select array_agg(value order by ordinality) into picked
  from jsonb_array_elements_text(chosen) with ordinality;
  if random() < 0.38 and array_length(picked, 1) > 1 then return array[picked[1]]; end if;
  return picked;
end;
$$;

create or replace function public.room_state(p_token text)
returns jsonb language plpgsql security definer
set search_path = public, private
as $$
declare
  identity_name text := private.token_identity(p_token);
  message_list jsonb;
  people_count bigint;
begin
  if identity_name is null then return jsonb_build_object('ok', false, 'error', '登录已过期。'); end if;
  select coalesce(jsonb_agg(to_jsonb(m) order by m.id), '[]'::jsonb) into message_list
  from (select id, sender, body, created_at from public.messages order by id desc limit 200) m;
  select count(*) + 1 into people_count from public.participants;
  return jsonb_build_object('ok', true, 'role', identity_name, 'messages', message_list, 'participantCount', people_count);
end;
$$;

create or replace function public.room_send(p_token text, p_body text)
returns jsonb language plpgsql security definer
set search_path = public, private
as $$
declare
  identity_name text := private.token_identity(p_token);
  clean_body text := left(trim(coalesce(p_body, '')), 1000);
  should_reply boolean;
  reply text;
begin
  if identity_name is null then return jsonb_build_object('ok', false, 'error', '登录已过期。'); end if;
  if clean_body = '' then return jsonb_build_object('ok', false, 'error', '你倒是说点什么。'); end if;
  insert into public.messages(sender, body) values (identity_name, clean_body);
  -- 每条真人消息都让欠欠接话。
  should_reply := true;
  foreach reply in array private.qian_replies(clean_body, identity_name) loop
    insert into public.messages(sender, body) values ('欠欠', reply);
  end loop;
  return jsonb_build_object('ok', true, 'askQian', false);
end;
$$;

create or replace function public.room_qian_fallback(p_token text, p_body text)
returns jsonb language plpgsql security definer
set search_path = public, private
as $$
declare
  identity_name text := private.token_identity(p_token);
  reply text;
begin
  if identity_name is null then return jsonb_build_object('ok', false); end if;
  foreach reply in array private.qian_replies(left(trim(coalesce(p_body, '')), 1000), identity_name) loop
    insert into public.messages(sender, body) values ('欠欠', reply);
  end loop;
  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.room_login(text, text) from public;
revoke all on function public.room_state(text) from public;
revoke all on function public.room_send(text, text) from public;
revoke all on function public.room_qian_fallback(text, text) from public;
grant execute on function public.room_login(text, text) to anon, authenticated;
grant execute on function public.room_state(text) to anon, authenticated;
grant execute on function public.room_send(text, text) to anon, authenticated;
grant execute on function public.room_qian_fallback(text, text) to anon, authenticated;

-- Password hashes and the signing secret are configured separately in the dashboard.
