"use client";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
type ChatMessage = { id:number; sender:string; body:string; createdAt:string };
export default function Home(){
  const [role,setRole]=useState<string|null>(null),[checking,setChecking]=useState(true),[password,setPassword]=useState(""),[nickname,setNickname]=useState(""),[needNickname,setNeedNickname]=useState(false),[loginError,setLoginError]=useState(""),[messages,setMessages]=useState<ChatMessage[]>([]),[participantCount,setParticipantCount]=useState(0),[input,setInput]=useState(""),[sending,setSending]=useState(false);
  const bottom=useRef<HTMLDivElement>(null);
  const load=useCallback(async()=>{const response=await fetch("/api/messages",{cache:"no-store"});if(response.ok){const data=await response.json();setMessages(data.messages);setParticipantCount(data.participantCount??0)}},[]);
  useEffect(()=>{fetch("/api/login").then(r=>r.json()).then(data=>{if(data.authenticated)setRole(data.role);setChecking(false)}).catch(()=>setChecking(false))},[]);
  useEffect(()=>{if(!role)return;load();const timer=window.setInterval(load,1800);return()=>window.clearInterval(timer)},[role,load]);
  useEffect(()=>{ bottom.current?.scrollIntoView({behavior:"smooth"}); },[messages]);
  async function login(event:FormEvent){event.preventDefault();setLoginError("");const response=await fetch("/api/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password,nickname})});const data=await response.json();if(!response.ok){if(data.code==="nickname_required")setNeedNickname(true);setLoginError(data.error);return}setRole(data.role);setPassword("");setNickname("")}
  async function send(event:FormEvent){event.preventDefault();const body=input.trim();if(!body||sending)return;setSending(true);setInput("");const response=await fetch("/api/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body})});if(response.ok)await load();else setInput(body);setSending(false)}
  if(checking)return <main className="stage"><div className="checking">正在检查你是哪位……</div></main>;
  if(!role)return <main className="stage"><section className="gate"><div className="gate-icon">欠</div><p className="eyebrow">私人废话现场</p><h1>张兴宇翻译器</h1><p className="gate-copy">有链接不算数。报暗号，我看看你是谁。</p><form onSubmit={login}><input type="password" inputMode="numeric" value={password} onChange={e=>setPassword(e.target.value)} placeholder="输入你的密码" autoFocus aria-label="房间密码"/>{needNickname&&<input value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="给自己起个昵称" aria-label="访客昵称" maxLength={16}/>}<button disabled={!password||(needNickname&&!nickname.trim())}>让我进去</button></form>{loginError&&<p className="error">{loginError}</p>}<p className="privacy">专属密码对应固定身份；访客密码可以让不同昵称的人加入。消息会在房间里保存，里面的人都看得到。</p></section></main>;
  return <main className="stage"><section className="phone" aria-label="共享聊天室"><header className="topbar"><div className="avatar">欠</div><div className="identity"><h1>张兴宇翻译器</h1><p><span className="dot"/> 房间人数：{participantCount}</p></div><div className="status">你是：{role}</div></header><div className="notice">密码决定身份 · 消息每两秒同步 · 机器偶尔多嘴</div><div className="chat" aria-live="polite"><div className="day">废话现场</div>{messages.length===0&&<div className="empty">还没人说话。你先来，别怂。</div>}{messages.map(message=><div className={`row ${message.sender===role?"you":"bot"}`} key={message.id}>{message.sender!==role&&<div className={`mini-avatar sender-${message.sender}`}>{message.sender==="欠嘴机器"?"欠":message.sender.slice(0,1)}</div>}<div><div className="sender-name">{message.sender===role?"你":message.sender}</div><div className="bubble">{message.body}</div></div></div>)}<div ref={bottom}/></div><form className="composer" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder={`以“${role}”的身份说点什么…`} aria-label="输入消息" maxLength={1000}/><button disabled={!input.trim()||sending}>{sending?"…":"发送"}</button></form></section><p className="footnote">你们负责聊天，我负责在不该说话的时候说话。</p></main>;
}
